config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("review.urls")),
    path("follows/", include("follows.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path

from review import views


app_name = "review"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("ticket/créer/", views.TicketCreateView.as_view(), name="ticket_create"),
    path("ticket/<int:ticket_id>/modifier/", views.TicketUpdateView.as_view(), name="ticket_update"),
    path("ticket/<int:ticket_id>/supprimer/", views.TicketDeleteView.as_view(), name="ticket_delete"),
    path("ticket/<int:ticket_id>/critique/créer/", views.ReviewCreateView.as_view(), name="review_create"),
    path("review/<int:review_id>/critique/modifier/", views.ReviewUpdateView.as_view(), name="review_update"),
    path("review/<int:review_id>/supprimer/", views.ReviewDeleteView.as_view(), name="review_delete"),
    path("ticket-review/créer/", views.TicketReviewCreateView.as_view(), name="ticket_review_create"),
    path("my_posts/", views.UserPostsView.as_view(), name="user_posts"),
]

review/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Ticket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=128, verbose_name="Titre")
    description = models.TextField(max_length=2048, verbose_name="Description", blank=True)
    image = models.ImageField(blank=True, null=True, verbose_name="Image")
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Vérifie si une nouvelle image a été ajoutée
        if self.pk:
            old_ticket = Ticket.objects.get(pk=self.pk)
            if old_ticket.image and old_ticket.image != self.image:
                # Suppression de l'ancienne image
                old_ticket.image.delete(save=False)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Suppression de l'image associée
        if self.image:
            self.image.delete(save=False)
        super().delete(*args, **kwargs)


class Review(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name="reviews")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)], verbose_name="Note"
    )
    headline = models.CharField(max_length=128, verbose_name="Titre")
    body = models.TextField(max_length=8192, blank=True, verbose_name="Commentaire")
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.headline

review/forms.py
from django import forms

from review.models import Review, Ticket


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ["title", "description", "image"]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["headline", "rating", "body"]

review/views.py
from itertools import chain
from operator import attrgetter

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from follows.models import UserFollow
from review.forms import ReviewForm, TicketForm
from review.models import Review, Ticket
from review.permissions.edit_access import review_owner_required, ticket_owner_required


class HomeView(LoginRequiredMixin, View):
    template_name = "review/home.html"

    def get(self, request):
        user = request.user

        # Retrieve followed users
        followed_users = UserFollow.objects.get_followings(user).values_list("followed_user", flat=True)

        # Retrieve tickets and reviews from followed users + the user himself
        users_to_include = list(followed_users) + [user]

        tickets = Ticket.objects.filter(user__in=users_to_include)
        reviews = Review.objects.filter(user__in=users_to_include)

        # Create a dictionary associating each ticket with a boolean indicating
        # whether the user has already posted a review
        user_reviews = Review.objects.filter(user=user).values_list("ticket_id", flat=True)
        tickets_with_reviews = {ticket.id: ticket.id in user_reviews for ticket in tickets}

        # Merge the queries and sort by creation date (reverse chronological order)
        posts = sorted(list(tickets) + list(reviews), key=lambda post: post.time_created, reverse=True)

        return render(request, self.template_name, {"posts": posts, "tickets_with_reviews": tickets_with_reviews})


class TicketCreateView(LoginRequiredMixin, View):
    template_name = "review/ticket_form.html"

    def get(self, request):
        ticket_form = TicketForm()
        return render(request, self.template_name, {"ticket_form": ticket_form})

    def post(self, request):
        form = TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            messages.success(request, "Demande de critique publiée !")
            return redirect("review:home")
        return render(request, self.template_name, {"ticket_form": form})


@method_decorator(ticket_owner_required, name="dispatch")
class TicketUpdateView(LoginRequiredMixin, View):
    template_name = "review/ticket_form.html"

    def get(self, request, ticket_id):
        ticket = get_object_or_404(Ticket, id=ticket_id)
        ticket_form = TicketForm(instance=ticket)
        return render(request, self.template_name, {"ticket_form": ticket_form})

    def post(self, request, ticket_id):
        ticket = get_object_or_404(Ticket, id=ticket_id)
        form = TicketForm(request.POST, request.FILES, instance=ticket)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            messages.success(request, "Demande de critique mise à jour.")
            return redirect("review:user_posts")
        return render(request, self.template_name, {"ticket_form": form})


@method_decorator(ticket_owner_required, name="dispatch")
class TicketDeleteView(LoginRequiredMixin, View):
    template_name = "review/includes/delete_confirm.html"

    def get(self, request, ticket_id):
        ticket = get_object_or_404(Ticket, id=ticket_id)
        cancel_url = reverse("review:user_posts")
        return render(request, self.template_name, {"object": ticket, "cancel_url": cancel_url})

    def post(self, request, ticket_id):
        ticket = get_object_or_404(Ticket, id=ticket_id)
        ticket.delete()
        messages.success(request, "Demande de critique supprimée.")
        return redirect("review:user_posts")


class ReviewCreateView(LoginRequiredMixin, View):
    template_name = "review/review_form.html"

    def get(self, request, ticket_id):
        ticket = get_object_or_404(Ticket, id=ticket_id)
        review_form = ReviewForm()
        return render(request, self.template_name, {"review_form": review_form, "ticket": ticket})

    def post(self, request, ticket_id):
        ticket = get_object_or_404(Ticket, id=ticket_id)
        review_form = ReviewForm(request.POST)
        rating_input = request.POST.get("rating")
        if rating_input:
            try:
                rating_input = int(rating_input)
            except ValueError:
                review_form.add_error("rating", "La note doit être un nombre valide.")

        if review_form.is_valid():
            form_instance = review_form.save(commit=False)
            form_instance.user = request.user
            form_instance.ticket = ticket
            form_instance.rating = rating_input
            form_instance.save()
            messages.success(request, ("Merci pour votre commentaire !"))
            return redirect("review:home")

        return render(request, self.template_name, {"review_form": review_form, "ticket": ticket})


@method_decorator(review_owner_required, name="dispatch")
class ReviewUpdateView(LoginRequiredMixin, View):
    template_name = "review/review_form.html"

    def get(self, request, review_id):
        review = get_object_or_404(Review, id=review_id)
        review_form = ReviewForm(instance=review)
        return render(request, self.template_name, {"review_form": review_form, "ticket": review.ticket})

    def post(self, request, review_id):
        review = get_object_or_404(Review, id=review_id)
        review_form = ReviewForm(request.POST, instance=review)
        rating_input = request.POST.get("rating")
        if rating_input:
            try:
                rating_input = int(rating_input)
            except ValueError:
                review_form.add_error("rating", "La note doit être un nombre valide.")

        if review_form.is_valid():
            form_instance = review_form.save(commit=False)
            form_instance.user = request.user
            form_instance.rating = rating_input
            form_instance.save()
            messages.success(request, "Commentaire mis à jour !")
            return redirect("review:user_posts")
        return render(request, self.template_name, {"review_form": review_form, "ticket": review.ticket})


@method_decorator(review_owner_required, name="dispatch")
class ReviewDeleteView(LoginRequiredMixin, View):
    template_name = "review/includes/delete_confirm.html"

    def get(self, request, review_id):
        review = get_object_or_404(Review, id=review_id)
        cancel_url = reverse("review:user_posts")
        return render(request, self.template_name, {"object": review, "cancel_url": cancel_url})

    def post(self, request, review_id):
        review = get_object_or_404(Review, id=review_id)
        review.delete()
        messages.success(request, "Commentaire supprimé.")
        return redirect("review:user_posts")


class UserPostsView(LoginRequiredMixin, View):
    template_name = "review/user_posts.html"

    def get(self, request):
        tickets = Ticket.objects.filter(user=request.user)
        reviews = Review.objects.filter(user=request.user).select_related("ticket")
        combined_posts = list(chain(tickets, reviews))
        sorted_posts = sorted(combined_posts, key=attrgetter("time_created"), reverse=True)

        return render(request, self.template_name, {"posts": sorted_posts})


class TicketReviewCreateView(LoginRequiredMixin, View):
    template_name = "review/ticket_review_form.html"

    def get(self, request):
        ticket_form = TicketForm()
        review_form = ReviewForm()
        return render(request, self.template_name, {"ticket_form": ticket_form, "review_form": review_form})

    def post(self, request):
        ticket_form = TicketForm(request.POST, request.FILES)
        review_form = ReviewForm(request.POST)
        rating_input = request.POST.get("rating")
        if rating_input:
            try:
                rating_input = int(rating_input)
            except ValueError:
                review_form.add_error("rating", "La note doit être un nombre valide.")

        if ticket_form.is_valid() and review_form.is_valid():
            with transaction.atomic():
                ticket = ticket_form.save(commit=False)
                ticket.user = request.user
                ticket.save()
                review = review_form.save(commit=False)
                review.user = request.user
                review.ticket = ticket
                review.rating = rating_input
                review.save()
                messages.success(request, "Critique publiée !")
            return redirect("review:home")
        return render(request, self.template_name, {"ticket_form": ticket_form, "review_form": review_form})

review/templates/review/includes/delete_confirm.html
{% extends "base.html" %}
{% block content %}
<div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8 lg:py-32 flex flex-col items-center">
    <div class="max-w-md p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">Confirmer la suppression</h5>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
            Êtes-vous sûr de vouloir supprimer la demande de critique "{{ object }}" ? <br>
            Cette action est irréversible.
        </p>
        <div class="mt-5 text-right">
            <form method="post">
                {% csrf_token %}
                <a href="{{ cancel_url }}" class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">
                    Annuler
                </a>
                <button type="submit" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
                    Confirmer
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

review/templates/review/includes/review_card.html
{% load static %}
{% load custom_filters %}
<div class="w-full border border-gray-300 rounded-lg shadow-sm mb-5 p-5">
  <div class="flex justify-between">
    <div class="flex">
      {% if post.user == request.user %}
        <p class="me-5">Vous avez publié une critique</p>
      {% else %}
        <p>{{ post.user }} a publié une critique</p>
      {% endif %}
    </div>
    <p class="text-xs text-gray-700">
      <time datetime="{{ post.time_created }}">{{ post.time_created | date:"H:i, d F Y" }}</time>
    </p>
  </div>
  <h2 class="text-xl font-semibold my-5">
    {{ post.headline }} -
    <span class="inline-flex">
      {% for _ in post.rating|stars_count %}
        <img src="{% static 'medias/star.png' %}"
             alt="Note {{ forloop.counter }} étoiles"
             width="20"
             height="20">
      {% endfor %}
    </span>
  </h2>
  <p class="text-gray-700 mb-3">{{ post.body }}</p>
  {% include "review/includes/ticket_card.html" with ticket=post.ticket is_posts_page=True review_card=True %}
  {% if is_posts_page and post.user == request.user %}
    <div class="flex justify-end space-x-2 mt-3">
      <a href="{% url 'review:review_update' post.id %}"
         class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800"
         aria-label="Modifier la critique">Modifier</a>
      <a href="{% url 'review:review_delete' post.id %}"
         class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"
         aria-label="Supprimer la critique">Supprimer</a>
    </div>
  {% endif %}
</div>

review/templates/review/includes/review_inputs.html
<div class="mb-5">
  <label for="{{ review_form.headline.id_for_label }}"
         class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ review_form.headline.label }}</label>
  <input type="text"
         id="{{ review_form.headline.id_for_label }}"
         name="{{ review_form.headline.html_name }}"
         value="{% if review_form.headline.value %}{{ review_form.headline.value }}{% endif %}"
         aria-required="true"
         aria-describedby="{% if review_form.headline.errors %}{{ review_form.headline.id_for_label }}-error{% endif %}"
         class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
  {% if review_form.headline.errors %}
    <span id="{{ review_form.headline.id_for_label }}-error"
          class="text-red-600 text-md"
          role="alert">{{ review_form.headline.errors.0 }}</span>
  {% endif %}
</div>
<fieldset class="mb-5">
  <legend class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ review_form.rating.label }}</legend>
  <div class="flex">
    {% for i in "012345" %}
      {% with i|add:"0" as i_int %}
        <div class="flex items-center me-4">
          <input id="rating-inline-radio-{{ i_int }}"
                 type="radio"
                 value="{{ i_int }}"
                 name="{{ review_form.rating.name }}"
                 aria-required="true"
                 aria-describedby="{% if review_form.rating.errors %}{{ review_form.rating.id_for_label }}-error{% endif %}"
                 class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                 {% if review_form.rating.value == i_int %}checked{% endif %}>
          <label for="rating-inline-radio-{{ i_int }}"
                 class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">{{ i_int }}</label>
        </div>
      {% endwith %}
    {% endfor %}
  </div>
  {% if review_form.rating.errors %}
    <span id="{{ review_form.rating.id_for_label }}-error"
          class="text-red-600 text-md"
          role="alert">{{ review_form.rating.errors.0 }}</span>
  {% endif %}
</fieldset>
<div class="my-5">
  <label for="{{ review_form.body.id_for_label }}"
         class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ review_form.body.label }}</label>
  <textarea id="{{ review_form.body.id_for_label}}"
            name="{{ review_form.body.html_name }}"
            rows="4"
            class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Écrivez la critique ici..."
            aria-describedby="{% if review_form.body.errors %}{{ review_form.body.id_for_label }}-error{% endif %}">{% if review_form.instance.body %}{{review_form.instance.body}}{% endif %}</textarea>
  {% if review_form.body.errors %}
    <span id="{{ review_form.body.id_for_label }}-error"
          class="text-red-600 text-md"
          role="alert">{{ review_form.body.errors.0 }}</span>
  {% endif %}
</div>

review/templates/review/includes/ticket_card.html
{% load static %}
{% load custom_filters %}
<div class="border border-gray-300 rounded-lg shadow-sm mb-5 p-5">
  <div class="flex justify-between mb-5">
    <div class="flex">
      <p class="me-5">{{ ticket.user.username }} a demandé une critique</p>
    </div>
    <p class="text-xs text-gray-700">
      <time datetime="{{ ticket.time_created }}">{{ ticket.time_created | date:"H:i, d F Y" }}</time>
    </p>
  </div>
  <h2 class="text-xl font-bold">{{ ticket.title }}</h2>
  <p class="text-gray-700 mb-3">{{ ticket.description }}</p>
  <div class="flex justify-between">
    <img src="{% if ticket.image %}{{ ticket.image.url }}{% else %}{% static 'medias/no-image.jpg' %}{% endif %}"
         alt="Image concernant la demande de critique {{ ticket.title }}"
         class="border border-gray-300 w-[160px] h-[200px] object-contain"
         width="160"
         height="200">
    {% if not tickets_with_reviews|get_item:ticket.id %}
      <a href="{% url 'review:review_create' ticket.id %}"
         class="text-white h-min self-end bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
        Créer une critique
      </a>
    {% endif %}
  </div>
  {% if is_posts_page and ticket.user == request.user and not review_card %}
    <div class="flex justify-end space-x-2 mt-3">
      <a href="{% url 'review:ticket_update' ticket.id %}"
         class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800"
         aria-label="Modifier la demande de critique">Modifier</a>
      <a href="{% url 'review:ticket_delete' ticket.id %}"
         class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"
         aria-label="Supprimer la demande de critique">Supprimer</a>
    </div>
  {% endif %}
</div>

review/templates/review/includes/ticket_inputs.html
<div class="mb-5">
  <label for="{{ ticket_form.title.id_for_label }}"
         class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ ticket_form.title.label }}</label>
  <input type="text"
         id="{{ ticket_form.title.id_for_label }}"
         name="{{ ticket_form.title.html_name }}"
         value="{% if ticket_form.title.value %}{{ ticket_form.title.value }}{% endif %}"
         aria-required="true"
         aria-describedby="{% if ticket_form.title.errors %}{{ ticket_form.title.id_for_label }}-error{% endif %}"
         class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
  {% if ticket_form.title.errors %}
    <span id="{{ ticket_form.title.id_for_label }}-error"
          class="text-red-600 text-md"
          role="alert">{{ ticket_form.title.errors.0 }}</span>
  {% endif %}
</div>
<div class="mb-5">
  <label for="{{ ticket_form.description.id_for_label }}"
         class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
    {{ ticket_form.description.label }}
  </label>
  <textarea id="{{ ticket_form.description.id_for_label}}"
            name="{{ ticket_form.description.html_name }}"
            rows="4"
            class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Écrivez la description du ticket ici..."
            aria-describedby="{% if ticket_form.description.errors %}{{ ticket_form.description.id_for_label }}-error{% endif %}">{% if ticket_form.instance.description %}{{ticket_form.instance.description}}{% endif %}</textarea>
  {% if ticket_form.description.errors %}
    <span id="{{ ticket_form.description.id_for_label }}-error"
          class="text-red-600 text-md"
          role="alert">{{ ticket_form.description.errors.0 }}</span>
  {% endif %}
</div>
<div class="mb-5">
  {% if ticket_form.instance.image %}
    <div class="mb-5">
      <p>Image actuelle :</p>
      <img src="{{ ticket_form.instance.image.url }}"
           alt="Image actuelle de la demande de critique {{ ticket_form.instance.title }}"
           class="border border-gray-300 w-[160px] h-[200px] object-contain"
           width="160"
           height="200">
    </div>
  {% endif %}
  <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
         for="{{ ticket_form.image.id_for_label }}">{{ ticket_form.image.label }}</label>
  <input id="{{ ticket_form.image.id_for_label }}"
         name="{{ ticket_form.image.html_name }}"
         value="{% if ticket_form.image.value %}{{ ticket_form.image.value }}{% endif %}"
         type="file"
         class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
         aria-describedby="{% if ticket_form.image.errors %}{{ ticket_form.image.id_for_label }}-error{% endif %}" />
  {% if ticket_form.image.errors %}
    <span id="{{ ticket_form.image.id_for_label }}-error"
          class="text-red-600 text-md"
          role="alert">{{ ticket_form.image.errors.0 }}</span>
  {% endif %}
</div>