accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("inscription/", views.SignupView.as_view(), name="signup"),
    path("connexion/", views.LoginView.as_view(), name="login"),
    path("deconnexion/", views.logout_view, name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("review.urls")),
    path("follows/", include("follows.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

follows/urls.py
from django.urls import path

from follows import views

app_name = "follows"

urlpatterns = [
    path("", views.FollowsView.as_view(), name="follow_home"),
    path("unfollow/<int:user_id>", views.UnFollowHtmxView.as_view(), name="unfollow"),
    path("follow/", views.follow_user, name="follow"),
    path("search-users/", views.search_users, name="search_users"),
]

review/urls.py
from django.urls import path

from review import views


app_name = "review"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("ticket/créer/", views.TicketCreateView.as_view(), name="ticket_create"),
    path("ticket/<int:ticket_id>/modifier/", views.TicketUpdateView.as_view(), name="ticket_update"),
    path("ticket/<int:ticket_id>/supprimer/", views.TicketDeleteView.as_view(), name="ticket_delete"),
    path("ticket/<int:ticket_id>/critique/créer/", views.ReviewCreateView.as_view(), name="review_create"),
    path("review/<int:review_id>/critique/modifier/", views.ReviewUpdateView.as_view(), name="review_update"),
    path("review/<int:review_id>/supprimer/", views.ReviewDeleteView.as_view(), name="review_delete"),
    path("ticket-review/créer/", views.TicketReviewCreateView.as_view(), name="ticket_review_create"),
    path("my_posts/", views.UserPostsView.as_view(), name="user_posts"),
]

templates/includes/message.html
<div id="messages"
     hx-swap-oob="true"
     class="fixed -top-50 right-0 z-50 m-1">
  {% for message in messages %}
    <div id="alert-message"
         class="alert-message flex items-center p-4 mb-4 text-{{ message.level_tag }}-800 rounded-lg bg-{{ message.level_tag }}-50 dark:bg-gray-800 dark:text-{{ message.level_tag }}-400 transition-all opacity-100"
         role="alert"
         aria-live="assertive">
      <svg class="shrink-0 w-4 h-4"
           aria-hidden="true"
           xmlns="http://www.w3.org/2000/svg"
           fill="currentColor"
           viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
      </svg>
      <span class="sr-only">{{ message.level_tag | capfirst }} message</span>
      <div class="ms-3 text-sm font-medium">{{ message }}</div>
      <button type="button"
              class="ms-auto -mx-1.5 -my-1.5 bg-{{ message.level_tag }}-50 text-{{ message.level_tag }}-800 rounded-lg focus:ring-2 focus:ring-{{ message.level_tag }}-400 p-1.5 hover:bg-{{ message.level_tag }}-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-{{ message.level_tag }}-400 dark:hover:bg-gray-700"
              onclick="closeAlert(this)"
              aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3"
             aria-hidden="true"
             xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
        </svg>
      </button>
    </div>
  {% endfor %}
</div>

templates/includes/navbar.html
{% load static %}
<header>
  <nav class="relative bg-white border-gray-200 dark:bg-gray-900 shadow-sm dark:border-gray-700">
    <div class="max-w-screen-3xl flex flex-wrap items-center justify-between mx-auto p-4">
      <div class="hidden lg:flex flex-1"></div>
      <a href="{% url 'review:home' %}"
         class="flex justify-center items-center flex-1 py-2"
         aria-label="Retour à l'accueil">
        <img src="{% static 'medias/favicon-32x32.png' %}"
             alt="Logo LitRevu"
             width="32"
             height="32" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">LitRevu</span>
      </a>
      {% if user.is_authenticated %}
        <button data-collapse-toggle="navbar-default"
                type="button"
                class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="navbar-default"
                aria-expanded="false">
          <span class="sr-only">Ouverture du menu principal</span>
          <svg class="w-5 h-5"
               aria-hidden="true"
               role="img"
               aria-label="Menu"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15" />
          </svg>
        </button>
        <div class="hidden w-full lg:flex lg:flex-1 lg:w-auto" id="navbar-default">
          <ul class="w-full font-medium flex flex-col p-4 lg:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 lg:flex-row lg:space-x-8 rtl:space-x-reverse lg:mt-0 lg:border-0 lg:bg-white dark:bg-gray-800 lg:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <a href="{% url 'review:home' %}"
                 aria-current="{% if request.resolver_match.url_name == 'home' %}page{% endif %}"
                 class="block py-2 px-3 rounded lg:p-0 {% if request.resolver_match.url_name == 'home' %}text-white bg-blue-700 lg:bg-transparent lg:text-blue-700 lg:dark:text-blue-500{% else %}text-gray-900 hover:bg-gray-100 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 dark:text-white lg:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent{% endif %}">
                Flux
              </a>
            </li>
            <li>
              <a href="{% url 'review:user_posts' %}"
                 aria-current="{% if request.resolver_match.url_name == 'user_posts' %}page{% endif %}"
                 class="block py-2 px-3 rounded lg:p-0 {% if request.resolver_match.url_name == 'user_posts' %}text-white bg-blue-700 lg:bg-transparent lg:text-blue-700 lg:dark:text-blue-500{% else %}text-gray-900 hover:bg-gray-100 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 dark:text-white lg:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent{% endif %}">
                Posts
              </a>
            </li>
            <li>
              <a href="{% url 'follows:follow_home' %}"
                 aria-current="{% if request.resolver_match.url_name == 'follow_home' %}page{% endif %}"
                 class="block py-2 px-3 rounded lg:p-0 {% if request.resolver_match.url_name == 'follow_home' %}text-white bg-blue-700 lg:bg-transparent lg:text-blue-700 lg:dark:text-blue-500{% else %}text-gray-900 hover:bg-gray-100 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 dark:text-white lg:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent{% endif %}">
                Abonnements
              </a>
            </li>
            <li class="min-w-max">
              <a href="{% url "accounts:logout" %}"
                 class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 lg:p-0 dark:text-white lg:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent">Se deconnecter</a>
            </li>
          </ul>
        </div>
      {% else %}
        <div class="hidden lg:flex flex-1"></div>
      {% endif %}
    </div>
  </nav>
</header>